version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:2022.05
    steps:
      - checkout
      - run:
          name: Set AWS Environment
          command: |
            eb setenv my-env-name --region $AWS_DEFAULT_REGION
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build